---
# tasks file for rabbitmq (Ubuntu specific)

- name: Download RabbitMQ package
  become: yes
  get_url:
    url: "{{ rabbitmq_url }}"
    dest: "{{ rabbitmq_download_dir }}/rabbitmq-server-{{ rabbitmq_version }}.deb"
    sha256sum: "{{ rabbitmq_sha256sum }}"
  tags:
    - rabbitmq

- name: Install RabbitMQ package
  become: yes
  apt:
    deb: "{{ rabbitmq_download_dir }}/rabbitmq-server-{{ rabbitmq_version }}.deb"
    state: present
  tags:
    - rabbitmq
